on: push
name: Publish
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Mod
      uses: netgamer7/factorio-mod-portal-publish@master
      env:
        FACTORIO_PASSWORD: ${{ secrets.FACTORIO_PASSWORD }}
        FACTORIO_USER: ${{ secrets.FACTORIO_USER }}
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: github-workspace
        path: /github/workspace/*
